openapi: "3.0.1"
info:
  title: !Sub "${AWS::StackName}"
paths:
  /{account_to_mention}/stories:
    get:
      responses:
        default:
          description: "Default response for GET /{account_to_mention}/stories"
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "POST"
        uri: !Join [ '', ['arn:aws:apigateway:', !Ref 'AWS::Region', ':dynamodb:action/BatchWriteItem'] ]
        credentials:
          !GetAtt MainHttpApiRoleDynamoDB.Arn
        passthroughBehavior: never
        requestTemplates:
          application/json: |
            #set($inputRoot = $input.path('$'))
              {
                "RequestItems": {
                  "${self:resources.Resources.EventsTable.Properties.TableName}": [
                    #foreach($event in $inputRoot.event)
                      {
                        "PutRequest": {
                          "Item": {
                            "requestId" : { "S": "$event.requestContext.requestId" },
                            "account" : { "S": "$event.pathParameters.account_to_mention" },
                          }
                        }
                      }#if($foreach.hasNext),#end
                    #end
                  ]
                },
                "ReturnConsumedCapacity": "NONE",
                "ReturnItemCollectionMetrics": "NONE"
              }
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
    parameters:
    - name: "account_to_mention"
      in: "path"
      description: "Generated path parameter for account_to_mention"
      required: true
      schema:
        type: "string"
x-amazon-apigateway-importexport-version: "1.0"
x-amazon-apigateway-cors:
  allowMethods:
  - "GET"
  - "POST"
  - "HEAD"
  allowHeaders:
  - "*"
  allowOrigins:
  - "https://instastories.houessou.com"